#!/bin/sh

wpctl() {
    arg="$2"

    set -- "$1"
    if [ "$1" = set-volume ]; then
        set -- "$@" --limit=1.0
    fi

    set -- "$@" @DEFAULT_AUDIO_SINK@ "$arg"

    command wpctl "$@"
}

case "$BLOCK_BUTTON" in
    1) wpctl set-mute toggle ;;
    2) wpctl set-volume 2%- ;;
    3) wpctl set-volume 2%+ ;;
esac

. /home/mario/.config/scripts/statusbar/sb-theme

if wpctl get-volume | rg -q "[MUTED]"; then
    echo ""
    exit
fi

volume_frac="$(wpctl get-volume | cut -d' ' -f2)"
volume="$(echo "$volume_frac * 100 / 1" | bc)"

if [ -z "$volume" ]; then
    exit 1
fi

if [ "$volume" -gt 40 ]; then
    icon=" "
elif [ "$volume" -gt 15 ]; then
    icon=" "
else
    icon=" "
fi

echo "$icon$volume%"
